import { ComponentLoader } from 'adminjs';
export declare const componentLoader: ComponentLoader;
export declare const Components: {
    Dashboard: string;
    DisplayLink: string;
    DisplayNestedImage: string;
    PrintImage: string;
    DisplayImage: string;
    DisplayImageBig: string;
    ReferenceImage: string;
    ReferenceImageBig: string;
    DisplayLinkBig: string;
    DisplayNestedImageBig: string;
    IdQuerySaver: string;
    ExportCsv: string;
    ManyToManyEdit: string;
    ManyToManyShow: string;
    ManyToManyList: string;
    ImageList: string;
    EditJSONB: string;
    ShowJSONB: string;
};
