import { ComponentLoader } from "adminjs";
export declare const componentLoader: ComponentLoader;
export declare const Components: {
    Dashboard: string;
    DisplayLink: string;
    DisplayRank: string;
    DisplayNestedImage: string;
    PrintImage: string;
    BulkCollectionApprove: string;
    BulkPremiumCollectionApprove: string;
    BulkNormalCollectionApprove: string;
    BulkCollectionReject: string;
    DisplayImage: string;
    DisplayImageBig: string;
    DisplayStyleImage: string;
    ReferenceImage: string;
    ReferenceImageBig: string;
    DisplayLinkBig: string;
    DisplayNestedImageBig: string;
    IdQuerySaver: string;
    ExportCsv: string;
    ManyToManyEdit: string;
    ManyToManyShow: string;
    ManyToManyList: string;
    M2MFilter: string;
    JsonDiff: string;
    ImageList: string;
    PreserveQueryList: string;
    EditJSONB: string;
    ShowJSONB: string;
    ImageIdLink: string;
    LLMPromptIdLink: string;
    LimitTextLength: string;
    ImageEmbed: string;
    PlanAndModel: string;
    CopyAndAssign: string;
    AddEditedImage: string;
    ReferenceEditWithFilter: string;
};
